# Generated by Django 2.0.3 on 2018-03-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_site_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('value_a', models.IntegerField(default=0)),
                ('value_b', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='site',
            name='date',
        ),
        migrations.RemoveField(
            model_name='site',
            name='value_a',
        ),
        migrations.RemoveField(
            model_name='site',
            name='value_b',
        ),
        migrations.AddField(
            model_name='sitedata',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
